# 需要的包

In [14]:
# Load in our libraries
import pandas as pd
import numpy as np
import re
import sklearn
import xgboost as xgb
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

import plotly.offline as py
py.init_notebook_mode(connected=True)
import plotly.graph_objs as go
import plotly.tools as tls

import warnings
warnings.filterwarnings('ignore')

# Going to use these 5 base models for the stacking
from sklearn.ensemble import (RandomForestClassifier, AdaBoostClassifier, 
                              GradientBoostingClassifier, ExtraTreesClassifier)
from sklearn.svm import SVC
from sklearn.cross_validation import KFold
pd.set_option('display.float_format', lambda x: '%.3f' % x)
%matplotlib inline
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" #所有的变量信息都可以打印出来

# 数据处理


## 数据读取

In [15]:
types={'CUPS_CARD_IN': str,'SPEC_DISC_LVL': str,'TRANS_CHNL': str,'SPEC_DISC_TP': str,'CARD_BIN': str,'MCHNT_TP': str}
train = pd.read_csv('./data2/trans_dtl_train1.csv',dtype=types)
test  = pd.read_csv('./data2/trans_dtl_test1.csv',dtype=types)
target = pd.read_csv('./data2/bind_cards1.csv')
target.columns = ['encrypt_card_no']
target['target'] = '1'
full_data = [train, test]
all =pd.concat(full_data)
train.info()
train.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 312647 entries, 0 to 312646
Data columns (total 32 columns):
SETTLE_DT           312647 non-null int64
encrypt_mchnt_cd    312647 non-null object
TERM_ID             310599 non-null object
MCHNT_TP            311750 non-null object
CONN_IN             312647 non-null int64
LOC_TRANS_TM        312647 non-null int64
STI_TAKEOUT_IN      312647 non-null int64
TRANS_ST            312647 non-null int64
CARD_BIN            312642 non-null object
CARD_PROD           312647 non-null int64
CARD_ATTR           312647 non-null int64
CARD_MEDIA          312647 non-null int64
CARD_BRAND          312647 non-null int64
CARD_RANK           312647 non-null int64
ISS_INS_ID_CD       312647 non-null int64
ACQ_INS_ID_CD       312647 non-null int64
TRANS_ID            312647 non-null object
TRANS_CHNL          312642 non-null object
TRANS_AT            312647 non-null int64
RESP_CD1            312311 non-null object
RESP_CD3            311665 non-null object
RESP_CD4            311665 non-null object
SPEC_DISC_TP        311305 non-null object
SPEC_DISC_LVL       311305 non-null object
encrypt_card_no     312647 non-null object
CUPS_CARD_IN        312642 non-null object
TRANS_MD            312647 non-null int64
HCE_PROD_NM         312647 non-null object
TOUCH_TP            312647 non-null int64
HCE_PROD_IN         312647 non-null int64
NOPWD_PETTY_IN      312647 non-null int64
WHITE_MCHNT_IN      312647 non-null int64
dtypes: int64(18), object(14)
memory usage: 76.3+ MB

,SETTLE_DT,encrypt_mchnt_cd,TERM_ID,MCHNT_TP,CONN_IN,LOC_TRANS_TM,STI_TAKEOUT_IN,TRANS_ST,CARD_BIN,CARD_PROD,...,SPEC_DISC_TP,SPEC_DISC_LVL,encrypt_card_no,CUPS_CARD_IN,TRANS_MD,HCE_PROD_NM,TOUCH_TP,HCE_PROD_IN,NOPWD_PETTY_IN,WHITE_MCHNT_IN
0,20180612,42fc2d6c76d2048c9aded5dbfcd1a9e2,12042365,8220,1,72535,1,1,19620516,0,...,00,0,7ccca9ac2b0fa257c3f78e4a0a30730c,2,1,0,2,0,0,1
1,20180603,f7fcc1f8027ff424327f7f6a2a2da256,01080209,4816,1,175047,1,1,1962156831,3,...,03,0,82c32cbb47703f4c3e6fd4585bbab5ce,2,2,0,99,0,0,0
2,20180511,e552f7d0516b669e04cbecc16b0b6640,45880776,7011,0,73149,1,1,16628268,1,...,00,0,edd137b31c3112c69c5e9f7d366dd81d,2,2,0,2,0,0,0
3,20180602,047e9e99f210f924ba30260eab354531,10000001,8398,1,63544,1,1,1962309101,0,...,00,0,55342a18c527b31709f9ee9ba2663c59,2,2,Y,99,0,0,1
4,20180606,42fc2d6c76d2048c9aded5dbfcd1a9e2,12042426,8220,1,124212,1,1,19620516,0,...,00,0,953664ea99b5b2b3fddb08732a358aa7,2,1,0,2,0,0,1

## 数据统计

In [3]:
test.shape
train.shape
target['encrypt_card_no'].nunique()
test['encrypt_card_no'].nunique()
train['encrypt_card_no'].nunique()
all['encrypt_card_no'].nunique()

(1026305, 32)

(312647, 32)

1199

35001

11200

46201

## 提取简易特征 

根据卡号进行聚合

In [16]:
all_together =(train.groupby(['encrypt_card_no'])
                  .agg({'TRANS_AT': ['sum', 'mean', 'min', 'max','count'],'HCE_PROD_NM': ['min', 'max']}))

### rename column

In [6]:
all_together.columns = ["_".join(x) for x in all_together.columns.ravel()]
all_together=all_together.reset_index(level=['encrypt_card_no'],drop=False)
all_together

,encrypt_card_no,TRANS_AT_sum,TRANS_AT_mean,TRANS_AT_min,TRANS_AT_max,TRANS_AT_count,HCE_PROD_NM_min,HCE_PROD_NM_max
0,00050a15df80a709d3e4973543b27c7a,4050743,253171.438,2350,1500000,16,0,0
1,0007358abae98a7836c3ec09c3b51e61,320780,18869.412,0,50000,17,0,0
2,0007d0ed3744d407c461ad52f60ecaa5,304000,30400.000,0,60000,10,0,0
3,0020d72758cdcca8f26da50311342ca8,2313300,578325.000,0,771100,4,0,0
4,002127f76a64d304e9f19a85038bce4d,229900,229900.000,229900,229900,1,0,0
5,0025ee4190b5ab5fd5c03e2f05b0ab61,0,0.000,0,0,1,0,0
6,0027ac1b5fa9e2dafda079786de87806,4316800,479644.444,235900,712000,9,0,0
7,002b207ef6dd6243c1b7ef658991b66b,488020,69717.143,24400,151710,7,0,0
8,002b918b3ddd263f292732f80897f36d,1354500,67725.000,5000,568400,20,0,0
9,002fa8d7f3b253ef1386f87b73118b75,59342501,1561644.763,-1228,5500000,38,0,0
10,0037d23195ef7e6d667d0a67481bf67b,2328096,47512.163,0,182000,49,0,0
11,003c6d40940ae6d47e397ab11e4cde84,300000,100000.000,0,300000,3,0,0
12,004165ac5d4343b0adc8411eb5f76da4,30343570,1264315.417,0,5000000,24,0,0
13,0043f8aee662cbf1efa530ca00d8d7f5,30000,10000.000,0,30000,3,0,0
14,00444b8e4fbb693037f1e800320c3ef7,3198600,399825.000,163500,798000,8,0,0
15,00567910bb7fe4a023e5f7564c3d61fc,11450086,216039.358,-500000,1040900,53,0,0
16,0061b6078dabe265aee6d9f451f55ff1,172800,19200.000,9000,32900,9,0,0
17,0065f49891a101216352f664bf00c181,5803977,829139.571,14791,2292743,7,0,0
18,0066bf5fe06b98d9d1e44183d8121a2e,100000,100000.000,100000,100000,1,0,0
19,00694c99912246971e380d9822e1536c,714940,51067.143,0,500000,14,0,0
20,006eb75409a76c15ac4e5bf3cbc41484,270000,30000.000,10000,100000,9,0,0
21,0072889b347119418d264abaf92b749b,500000,83333.333,0,300000,6,0,0
22,007f86709f853163c4dc3b742b1c0761,1193156,198859.333,51156,300000,6,0,0
23,0084df017686f9a9855bdc3eb2c93b10,2093521,299074.429,32226,1562000,7,0,0
24,0085b13f6d5abf7b6f8db8b688a19cca,5600,101.818,0,200,55,0,0
25,0092ecbca64dfa99af52bcc2e8854c1d,0,0.000,0,0,1,0,0
26,009b54db36c39d7a2c9c5777d1f3c3ae,20000,10000.000,0,20000,2,0,0
27,00abfd4e0998da6ff283ed8391387bb8,615537,87933.857,0,220600,7,0,0
28,00adeb76500afe4fe934af215e31cfc7,0,0.000,0,0,2,0,0
29,00b5600caa2d00fe6483a95f4db4ec64,3200199,800049.750,800000,800199,4,0,0
...,...,...,...,...,...,...,...,...
11170,ff53e5004132f08645c044dc43faf5d1,346000,31454.545,0,100000,11,0,0
11171,ff59fb3847325f4d5bd7f3ba239902a5,1857897,123859.800,0,1200000,15,0,0
11172,ff5fa372d02f4fc2cec79c713f4aac2d,225700,75233.333,0,145800,3,0,0
11173,ff645ee4e4b310b0613ea96fdc707e94,1142370,30874.865,0,294000,37,0,0
11174,ff6f451409264ae1871d54abe791bc3c,138800,15422.222,2100,41900,9,0,Z
11175,ff70430f70102e374b852beeeff0663e,5057169,1685723.000,950619,2996550,3,0,0
11176,ff70dd0da883e1dd6d0258c58865a06e,156820,684.803,30,6190,229,0,0
11177,ff791fb7c804aefd3195d340cbb5c12e,182006,182006.000,182006,182006,1,0,0
11178,ff7f2d8b4684c05faecdecbbc9532a3a,1790000,298333.333,0,1400000,6,0,0
11179,ff8282cafee4579c23dbe8ba33ceacca,12487995,416266.500,0,2480472,30,0,0
11180,ff83f4f16f268a4146e17a261c2752f2,60145790,278452.731,0,1746066,216,0,0
11181,ff8487ad2449fbe122bc4be70a78285e,600000,100000.000,0,300000,6,0,0
11182,ff91e8b01a7f1a0c5af4991e2766552c,7157821,83230.477,0,170647,86,0,0
11183,ff9885751f892cb48ce448f943fd2ef6,60300,4020.000,0,39900,15,0,0
11184,ff9fb08bec61142afd660ecff547c6c0,7989700,998712.500,1200,1995000,8,0,0
11185,ffb676c9d1ba6e60b8ac31ecea127380,595782,49648.500,19893,120000,12,0,0
11186,ffc28a933586c9560891f5537b8cbd03,124476,13830.667,0,41700,9,0,0
11187,ffc8616a7cf17d9b0bf2cfe152c6c54a,50000,50000.000,50000,50000,1,0,0
11188,ffc8e5ce110f50c1aab41b45579e8e18,965900,68992.857,10000,200000,14,0,0
11189,ffcd5ffd9677fac9a808ce8daeaf67e2,0,0.000,0,0,4,0,0
11190,ffdc0a48551cb57dbe18293f7a12f910,9399000,783250.000,29000,1600000,12,0,0
11191,ffe163444af1f5ee75b11903598fb284,182946,18294.600,0,100000,10,0,0
11192,ffec483b2c6479a8ad8c384c9752395b,0,0.000,0,0,3,0,0
11193,ffeeb4af4f57ef7d17f10e45567636e7,1357700,169712.500,50000,514000,8,0,0
11194,ffeebc366a30fada67b4373e4dcd59a1,6812131,619284.636,40466,5000000,11,0,0
11195,fff0481ece235ca27a8bb495b6142001,430000,47777.778,0,200000,9,0,0
11196,fff2bfa0858b0a483c89c48033a72cab,633200,70355.556,0,500000,9,0,0
11197,fff870d960a247d4edb6d96285480df8,0,0.000,0,0,3,0,0
11198,fffdcc45454deed79f8a3169428c1824,68000,68000.000,68000,68000,1,0,0
11199,ffff28687fec8868095e3f6adb686e0b,5080,725.714,314,1500,7,Y,Y

## 打标签


###  直接打标签

根据bind_cards1.csv打标签，绑定云闪付的为1，不绑定的为0

In [8]:
train_v=pd.merge(all_together, target, on='encrypt_card_no', how='outer')
train_v.fillna(value=0)

,encrypt_card_no,TRANS_AT_sum,TRANS_AT_mean,TRANS_AT_min,TRANS_AT_max,TRANS_AT_count,HCE_PROD_NM_min,HCE_PROD_NM_max,target
0,00050a15df80a709d3e4973543b27c7a,4050743,253171.438,2350,1500000,16,0,0,0
1,0007358abae98a7836c3ec09c3b51e61,320780,18869.412,0,50000,17,0,0,0
2,0007d0ed3744d407c461ad52f60ecaa5,304000,30400.000,0,60000,10,0,0,0
3,0020d72758cdcca8f26da50311342ca8,2313300,578325.000,0,771100,4,0,0,0
4,002127f76a64d304e9f19a85038bce4d,229900,229900.000,229900,229900,1,0,0,0
5,0025ee4190b5ab5fd5c03e2f05b0ab61,0,0.000,0,0,1,0,0,0
6,0027ac1b5fa9e2dafda079786de87806,4316800,479644.444,235900,712000,9,0,0,0
7,002b207ef6dd6243c1b7ef658991b66b,488020,69717.143,24400,151710,7,0,0,0
8,002b918b3ddd263f292732f80897f36d,1354500,67725.000,5000,568400,20,0,0,0
9,002fa8d7f3b253ef1386f87b73118b75,59342501,1561644.763,-1228,5500000,38,0,0,1
10,0037d23195ef7e6d667d0a67481bf67b,2328096,47512.163,0,182000,49,0,0,0
11,003c6d40940ae6d47e397ab11e4cde84,300000,100000.000,0,300000,3,0,0,0
12,004165ac5d4343b0adc8411eb5f76da4,30343570,1264315.417,0,5000000,24,0,0,0
13,0043f8aee662cbf1efa530ca00d8d7f5,30000,10000.000,0,30000,3,0,0,0
14,00444b8e4fbb693037f1e800320c3ef7,3198600,399825.000,163500,798000,8,0,0,0
15,00567910bb7fe4a023e5f7564c3d61fc,11450086,216039.358,-500000,1040900,53,0,0,1
16,0061b6078dabe265aee6d9f451f55ff1,172800,19200.000,9000,32900,9,0,0,1
17,0065f49891a101216352f664bf00c181,5803977,829139.571,14791,2292743,7,0,0,0
18,0066bf5fe06b98d9d1e44183d8121a2e,100000,100000.000,100000,100000,1,0,0,1
19,00694c99912246971e380d9822e1536c,714940,51067.143,0,500000,14,0,0,0
20,006eb75409a76c15ac4e5bf3cbc41484,270000,30000.000,10000,100000,9,0,0,0
21,0072889b347119418d264abaf92b749b,500000,83333.333,0,300000,6,0,0,0
22,007f86709f853163c4dc3b742b1c0761,1193156,198859.333,51156,300000,6,0,0,0
23,0084df017686f9a9855bdc3eb2c93b10,2093521,299074.429,32226,1562000,7,0,0,0
24,0085b13f6d5abf7b6f8db8b688a19cca,5600,101.818,0,200,55,0,0,0
25,0092ecbca64dfa99af52bcc2e8854c1d,0,0.000,0,0,1,0,0,0
26,009b54db36c39d7a2c9c5777d1f3c3ae,20000,10000.000,0,20000,2,0,0,1
27,00abfd4e0998da6ff283ed8391387bb8,615537,87933.857,0,220600,7,0,0,1
28,00adeb76500afe4fe934af215e31cfc7,0,0.000,0,0,2,0,0,0
29,00b5600caa2d00fe6483a95f4db4ec64,3200199,800049.750,800000,800199,4,0,0,0
...,...,...,...,...,...,...,...,...,...
11170,ff53e5004132f08645c044dc43faf5d1,346000,31454.545,0,100000,11,0,0,0
11171,ff59fb3847325f4d5bd7f3ba239902a5,1857897,123859.800,0,1200000,15,0,0,1
11172,ff5fa372d02f4fc2cec79c713f4aac2d,225700,75233.333,0,145800,3,0,0,0
11173,ff645ee4e4b310b0613ea96fdc707e94,1142370,30874.865,0,294000,37,0,0,0
11174,ff6f451409264ae1871d54abe791bc3c,138800,15422.222,2100,41900,9,0,Z,0
11175,ff70430f70102e374b852beeeff0663e,5057169,1685723.000,950619,2996550,3,0,0,0
11176,ff70dd0da883e1dd6d0258c58865a06e,156820,684.803,30,6190,229,0,0,0
11177,ff791fb7c804aefd3195d340cbb5c12e,182006,182006.000,182006,182006,1,0,0,1
11178,ff7f2d8b4684c05faecdecbbc9532a3a,1790000,298333.333,0,1400000,6,0,0,0
11179,ff8282cafee4579c23dbe8ba33ceacca,12487995,416266.500,0,2480472,30,0,0,0
11180,ff83f4f16f268a4146e17a261c2752f2,60145790,278452.731,0,1746066,216,0,0,0
11181,ff8487ad2449fbe122bc4be70a78285e,600000,100000.000,0,300000,6,0,0,0
11182,ff91e8b01a7f1a0c5af4991e2766552c,7157821,83230.477,0,170647,86,0,0,0
11183,ff9885751f892cb48ce448f943fd2ef6,60300,4020.000,0,39900,15,0,0,0
11184,ff9fb08bec61142afd660ecff547c6c0,7989700,998712.500,1200,1995000,8,0,0,0
11185,ffb676c9d1ba6e60b8ac31ecea127380,595782,49648.500,19893,120000,12,0,0,0
11186,ffc28a933586c9560891f5537b8cbd03,124476,13830.667,0,41700,9,0,0,0
11187,ffc8616a7cf17d9b0bf2cfe152c6c54a,50000,50000.000,50000,50000,1,0,0,1
11188,ffc8e5ce110f50c1aab41b45579e8e18,965900,68992.857,10000,200000,14,0,0,0
11189,ffcd5ffd9677fac9a808ce8daeaf67e2,0,0.000,0,0,4,0,0,0
11190,ffdc0a48551cb57dbe18293f7a12f910,9399000,783250.000,29000,1600000,12,0,0,0
11191,ffe163444af1f5ee75b11903598fb284,182946,18294.600,0,100000,10,0,0,0
11192,ffec483b2c6479a8ad8c384c9752395b,0,0.000,0,0,3,0,0,0
11193,ffeeb4af4f57ef7d17f10e45567636e7,1357700,169712.500,50000,514000,8,0,0,0
11194,ffeebc366a30fada67b4373e4dcd59a1,6812131,619284.636,40466,5000000,11,0,0,0
11195,fff0481ece235ca27a8bb495b6142001,430000,47777.778,0,200000,9,0,0,0
11196,fff2bfa0858b0a483c89c48033a72cab,633200,70355.556,0,500000,9,0,0,0
11197,fff870d960a247d4edb6d96285480df8,0,0.000,0,0,3,0,0,1
11198,fffdcc45454deed79f8a3169428c1824,68000,68000.000,68000,68000,1,0,0,0
11199,ffff28687fec8868095e3f6adb686e0b,5080,725.714,314,1500,7,Y,Y,0

In [9]:
train_v.query('HCE_PROD_NM_max != "0" and target == "1"' )

,encrypt_card_no,TRANS_AT_sum,TRANS_AT_mean,TRANS_AT_min,TRANS_AT_max,TRANS_AT_count,HCE_PROD_NM_min,HCE_PROD_NM_max,target
77,01cc8ed4c6932aa05e9ea295998b3b67,29494100,116118.504,0,1988800,254,0,Z,1
162,03de3de5f9ee59460a9079e4ebc1630a,207535,15964.231,0,206000,13,0,Y,1
376,090b11b3a189f1f904726ed6853edafc,700,350.000,200,500,2,Y,Y,1
485,0b66970e2492c815b7b22da10a969df9,135300,19328.571,0,66100,7,0,Y,1
494,0ba55a8be080f6c237ba12d3d65c2b08,6301,1260.200,1,2100,5,Y,Z,1
506,0c05ee267edabae6c9fd5239b218cd71,90647,5665.438,0,61000,16,0,Y,1
580,0d7f1a2a48da25c7010bd920f63cf2f6,2966393,82399.806,0,500000,36,0,Y,1
663,0f7a2ff00c4db88b4381a1f22974b6d6,7259527,82494.625,0,2125903,88,0,Z,1
750,11b67b55d0e68a56c5802e9432574c9a,5099,1699.667,200,4699,3,1,1,1
851,13b346ffa087a1aeafff55f51e39244f,1722599,246085.571,599,1500000,7,0,6,1
989,16bd3c0a5408a766272c8850aaa6fd10,30072774,2004851.600,10000,4530000,15,0,Y,1
1122,19a5b98a9174c3c86c55ea3fc4660088,5124253,341616.867,0,4999000,15,0,Y,1
1147,1a36cbf788018b9a293fdd2c7b976762,30000,4285.714,0,30000,7,0,Y,1
1241,1c6c7b1b0a87f87333838a123c8dbb1a,816570,22069.459,-30000,150000,37,0,1,1
1244,1c72a39c431727df27cb6d59d213d646,1483200,296640.000,300,950000,5,0,4,1
1498,21a0bf5aed404e05ceeea87046bb0b5e,998873,38418.192,0,561000,26,0,Y,1
1583,2356211e546d503af91f2176fc22e2c5,520400,130100.000,200,500000,4,0,Y,1
1838,2939aae4191009fbbb943517768928b6,393210,98302.500,11210,178100,4,0,1,1
1890,2a6f235a35b2ae64e3dfb922bc82408d,76545,9568.125,-4800,31697,8,0,Z,1
1995,2cfd258771e93cd224c2373000fd6e53,45520,2528.889,0,11782,18,0,Z,1
2012,2d5944aabbdf9fc0504b011160426053,701950,58495.833,0,150400,12,0,1,1
2072,2ec5a69a683b242c32b841d0fae454de,50583,3613.071,0,12378,14,0,Z,1
2188,318a3c5584f72bf639b6f5c70a9d6a2c,13345,2669.000,-445,3530,5,0,1,1
2542,38f35d7fc882a875c97e3fe47c75f239,1264786,84319.067,-6400,500000,15,0,Y,1
2629,3a7e29915276eca59117ff78a9c9699f,93700,683.942,0,50000,137,0,Y,1
2651,3afa5b8947c110b1b9ddf468df93d267,21500,2687.500,0,19000,8,0,Y,1
2753,3d6b69fc96d1e81cb56590e00fff2cae,100,50.000,0,100,2,0,Y,1
2776,3df5d2061b56ef36c63fe9aaa94d4fe8,24040,8013.333,3960,13700,3,Z,Z,1
2910,40678e68fa072889f4dfa627f06d353f,3,1.000,1,1,3,1,1,1
2963,416a04c17d8877d184bedf151b6a4e8f,232300,13664.706,0,26800,17,0,1,1
...,...,...,...,...,...,...,...,...,...
8379,be05221275b58b1331a58b18b96b0cbc,101,10.100,0,100,10,0,Y,1
8781,c7385f4e81abcb8ccbdc8bd9cff5a316,115000,57500.000,45000,70000,2,Y,Y,1
8875,c9821e997e37b8e997d1a721a0835041,109174,21834.800,7200,69359,5,0,1,1
8995,cc62da78560df9e9adcedecbd47f92c7,99730,7671.538,0,55623,13,0,Z,1
9020,ccfca406af1b0d51b242b577a88c9c04,2598911,66638.744,2100,360000,39,0,6,1
9058,cdc8b172487ce1f8cc51545cbcd071a7,1623200,231885.714,0,966600,7,0,Z,1
9195,d1070ad21aac1dd3a3e3cdef22359be3,1800,200.000,200,200,9,Y,Y,1
9294,d35d7f80edf3e913d9684082de8e37f2,9133095,126848.542,0,1000000,72,0,Y,1
9460,d753d17985ba7d6b8963b2057c2ddb49,10,1.667,0,10,6,0,Y,1
9708,dd1ee43be488574a8f6d1e23dc379a69,827200,33088.000,100,320000,25,0,Y,1
9840,e05884108fdc421eff1c5c130d7475af,85000,17000.000,0,60000,5,0,Y,1
9851,e0a056efab3572ef4fb5e0a4fa8f49ab,15162495,248565.492,0,8526017,61,0,Y,1
10024,e4ec5a51e1f0f60a5b9294adfaed721b,19105,406.489,0,884,47,0,Y,1
10075,e6018ffb6dd7149220e03c3eae8c111e,1811886,54905.636,-5000,300000,33,0,Y,1
10108,e6bfdb79ad4bd456c8378b997b520256,9588,355.111,0,1144,27,0,Z,1
10143,e7767047f3cef193f107ce9e05f18d09,66000,2129.032,0,20000,31,0,Y,1
10211,e8e33d571fa25163c044befb95f5e23b,1,1.000,1,1,1,Y,Y,1
10269,ea4d556d988f073f53ceeae5cd20996f,10517,318.697,0,5000,33,0,Y,1
10317,eba70c25c31d397eefa187ca31c74569,220000,27500.000,0,70000,8,0,Y,1
10339,ec54c1b07b764253c27427c87233abf7,1866100,84822.727,16800,100000,22,0,1,1
10385,ed8d31418ca5de88e2836014a4779f0e,80804,8080.400,0,18921,10,0,1,1
10554,f1cbd8bd514b8e967fbd2e4b40fb7777,20140400,559455.556,23000,1651000,36,0,1,1
10599,f28703f110e54ca023aeadb274997d12,1150,115.000,0,500,10,0,Z,1
10629,f31d2e433d51a177f5e359bc0a1316a7,962290,80190.833,12030,156600,12,0,1,1
10709,f4eaf6a209c90bcc1d0a24cacca28d0c,424179,18442.565,0,100000,23,0,Z,1
10724,f534d0949e9a56b38a0c2e6a5a9fa196,8037500,803750.000,10000,1000000,10,Y,Z,1
10758,f5ed102290148fe3c617bd2eed8d1d8a,706747,16062.432,0,259400,44,0,1,1
10872,f87d281a3aab5675e77fbb818f43ca87,100,20.000,0,100,5,0,Y,1
10895,f90d5df57fd229d4a029fbac948da6b5,6,0.857,0,6,7,0,Y,1
11104,fdea8b12804217c683597d98ece7b492,117003757,991557.263,0,5000000,118,0,Y,1

0-无产品          1-Apple Pay       2-HCE       3-三星pay mst  4-三星pay ic  5-线上大商户          6-华为          7-小米          8-中兴          Y-主扫         Z-被扫

In [10]:
train.groupby('HCE_PROD_NM').size()

HCE_PROD_NM
0    305217
1      1951
2        43
4        10
6        85
7         9
Y      4145
Z      1187
dtype: int64

# 结果文件

In [ ]:
a=train.loc[test['HCE_PROD_NM'] != '0'].encrypt_card_no.unique()
s=pd.Series(a)
s.to_csv('2.csv',index=False)

In [137]:
a=test.loc[test['HCE_PROD_NM'] != '0'].encrypt_card_no.unique()
pd.DataFrame(a).to_csv("1.csv",header=False,index=False)